// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe2CVvum173EUvIwEUfbreF0U82cr3Z6Q',
    appId: '1:440995731038:web:24d25950fd261e8ce546cf',
    messagingSenderId: '440995731038',
    projectId: 'richzspot-mobile',
    authDomain: 'richzspot-mobile.firebaseapp.com',
    storageBucket: 'richzspot-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSVcLtuR8484D1s4Esvo2NLdPyOXL-kqk',
    appId: '1:440995731038:android:3cd80cb460b4f994e546cf',
    messagingSenderId: '440995731038',
    projectId: 'richzspot-mobile',
    storageBucket: 'richzspot-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQBFL6EPWH-9XYkk0oHKdFycNK-hf0f_8',
    appId: '1:440995731038:ios:dfbcf4af246fb10ae546cf',
    messagingSenderId: '440995731038',
    projectId: 'richzspot-mobile',
    storageBucket: 'richzspot-mobile.firebasestorage.app',
    iosBundleId: 'com.example.richzspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQBFL6EPWH-9XYkk0oHKdFycNK-hf0f_8',
    appId: '1:440995731038:ios:dfbcf4af246fb10ae546cf',
    messagingSenderId: '440995731038',
    projectId: 'richzspot-mobile',
    storageBucket: 'richzspot-mobile.firebasestorage.app',
    iosBundleId: 'com.example.richzspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe2CVvum173EUvIwEUfbreF0U82cr3Z6Q',
    appId: '1:440995731038:web:76c74e5d03b17cbce546cf',
    messagingSenderId: '440995731038',
    projectId: 'richzspot-mobile',
    authDomain: 'richzspot-mobile.firebaseapp.com',
    storageBucket: 'richzspot-mobile.firebasestorage.app',
  );

}