// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH6F6sn6VZoSEWI3YxWejcsiXHcxuAoHY',
    appId: '1:324674983335:web:ef4c451e92cb31807a9282',
    messagingSenderId: '324674983335',
    projectId: 'richzspotnewmobile',
    authDomain: 'richzspotnewmobile.firebaseapp.com',
    storageBucket: 'richzspotnewmobile.firebasestorage.app',
    measurementId: 'G-T7CH8WF59Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTmSzs6NOE6O2JLqp68Dbok-b5s9cIFyk',
    appId: '1:324674983335:android:298ae88d68a6daaa7a9282',
    messagingSenderId: '324674983335',
    projectId: 'richzspotnewmobile',
    storageBucket: 'richzspotnewmobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxHKOqQUwf3evQSrWaCrCskPSzuqDbK88',
    appId: '1:324674983335:ios:e9ab2aa1a90daae17a9282',
    messagingSenderId: '324674983335',
    projectId: 'richzspotnewmobile',
    storageBucket: 'richzspotnewmobile.firebasestorage.app',
    iosBundleId: 'com.example.richzspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxHKOqQUwf3evQSrWaCrCskPSzuqDbK88',
    appId: '1:324674983335:ios:e9ab2aa1a90daae17a9282',
    messagingSenderId: '324674983335',
    projectId: 'richzspotnewmobile',
    storageBucket: 'richzspotnewmobile.firebasestorage.app',
    iosBundleId: 'com.example.richzspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH6F6sn6VZoSEWI3YxWejcsiXHcxuAoHY',
    appId: '1:324674983335:web:326dd6f7e6864eec7a9282',
    messagingSenderId: '324674983335',
    projectId: 'richzspotnewmobile',
    authDomain: 'richzspotnewmobile.firebaseapp.com',
    storageBucket: 'richzspotnewmobile.firebasestorage.app',
    measurementId: 'G-037QQBG4R2',
  );

}